# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WuMkLhePNbW3SfxE0G-Dik8wwutfZMI7
"""

print("Hello, Big Data!")

my_name = "kennie Ineza"
my_age = 20
my_gpa = 3.55
am_i_present = True

print(my_name, type(my_name))
print(my_age, type(my_age))
print(my_gpa, type(my_gpa))
print(am_i_present, type(am_i_present))

age_text = "20"
age_int = int(age_text)
new_age = age_int + 1
print(new_age)

print("3" + "4")

"""it doesnot give seven because "3" and "4" as given are strings and + sign does not do addition as it does for other numbers but it joins the strings together."""

print(f"I am {my_name}, {my_age} years old, studying at AUCA.")

course = "Big Data Analytics"

print(course.upper())
print(len(course))
print(course[0:3])

scores = [72, 85, 91, 64, 78]

print("First score:", scores[0])
print("Last score:", scores[-1])
print("Number of scores:", len(scores))
print("Average:", sum(scores) / len(scores))
print("Highest:", max(scores))
print("Lowest:", min(scores))

scores = [72, 85, 91, 64, 78]

scores.append(88)
scores[3] = 66

print("Updated list:", scores)
print("New average:", sum(scores) / len(scores))

me = {
    "name": "Kennie Ineza",
    "age": 20,
    "program": "Software Engineering",
    "district": "Kamonyi"
}

print(me["program"])

me["score"] = 88
me["age"] = me["age"] + 1

print(me.keys())
print(me)

students = [
    {"ID":"AUCA001","Name":"Aline Uwase","Age":21,"Gender":"F","Program":"Information Systems","District":"Gasabo","Att. %":92,"Score":85},
    {"ID":"AUCA002","Name":"Eric Niyonzima","Age":23,"Gender":"M","Program":"Software Engineering","District":"Kicukiro","Att. %":88,"Score":78},
    {"ID":"AUCA003","Name":"Diane Mukamana","Age":20,"Gender":"F","Program":"Information Systems","District":"Nyarugenge","Att. %":95,"Score":91},
    {"ID":"AUCA004","Name":"Jean Bosco Habimana","Age":24,"Gender":"M","Program":"Networking","District":"Gasabo","Att. %":70,"Score":64},
    {"ID":"AUCA005","Name":"Clarisse Ingabire","Age":22,"Gender":"F","Program":"Accounting","District":"Musanze","Att. %":85,"Score":72},
    {"ID":"AUCA006","Name":"Patrick Mugisha","Age":21,"Gender":"M","Program":"Software Engineering","District":"Huye","Att. %":90,"Score":83},
    {"ID":"AUCA007","Name":"Sandrine Umutoni","Age":19,"Gender":"F","Program":"Information Systems","District":"Kicukiro","Att. %":97,"Score":94},
    {"ID":"AUCA008","Name":"Emmanuel Nsengiyumva","Age":25,"Gender":"M","Program":"Networking","District":"Rubavu","Att. %":65,"Score":58},
    {"ID":"AUCA009","Name":"Grace Uwimana","Age":20,"Gender":"F","Program":"Accounting","District":"Gasabo","Att. %":82,"Score":76},
    {"ID":"AUCA010","Name":"Yves Ndayisenga","Age":22,"Gender":"M","Program":"Software Engineering","District":"Nyarugenge","Att. %":78,"Score":69},
    {"ID":"AUCA011","Name":"Josiane Mukeshimana","Age":21,"Gender":"F","Program":"Information Systems","District":"Muhanga","Att. %":93,"Score":88},
    {"ID":"AUCA012","Name":"Claude Iradukunda","Age":23,"Gender":"M","Program":"Networking","District":"Gasabo","Att. %":75,"Score":66},
    {"ID":"AUCA013","Name":"Beata Nyarhabimana","Age":24,"Gender":"F","Program":"Accounting","District":"Nyamagabe","Att. %":89,"Score":81},
    {"ID":"AUCA014","Name":"Olivier Twagirimana","Age":20,"Gender":"M","Program":"Software Engineering","District":"Kicukiro","Att. %":96,"Score":90},
    {"ID":"AUCA015","Name":"Chantal Uwera","Age":22,"Gender":"F","Program":"Information Systems","District":"Rusizi","Att. %":68,"Score":61},
    {"ID":"AUCA016","Name":"Fabrice Byiringiro","Age":21,"Gender":"M","Program":"Networking","District":"Musanze","Att. %":84,"Score":74},
    {"ID":"AUCA017","Name":"Solange Ishimwe","Age":19,"Gender":"F","Program":"Software Engineering","District":"Gasabo","Att. %":91,"Score":87},
    {"ID":"AUCA018","Name":"David Hakizimana","Age":25,"Gender":"M","Program":"Accounting","District":"Nyagatare","Att. %":72,"Score":55},
    {"ID":"AUCA019","Name":"Immaculee Uwamahoro","Age":23,"Gender":"F","Program":"Information Systems","District":"Kicukiro","Att. %":87,"Score":79},
    {"ID":"AUCA020","Name":"Samuel Rukundo","Age":20,"Gender":"M","Program":"Networking","District":"Nyarugenge","Att. %":94,"Score":92},
]

names = [s["Name"] for s in students]
all_scores = [s["Score"] for s in students]
districts = [s["District"] for s in students]

print(f"(a) Number of students: {len(students)}")
print(f"(b) Class average score: {round(sum(all_scores)/len(all_scores), 1)}")
print(f"(c) Highest score: {max(all_scores)}, Lowest score: {min(all_scores)}")
print(f"(d) Range: {max(all_scores) - min(all_scores)}")

print("First student:", students[0])
print("Last student:", students[-1])

s = students[6]
print(f"{s['Name']} from {s['District']} studies {s['Program']} and scored {s['Score']}.")

print("Gasabo:", districts.count("Gasabo"))
print("Kicukiro:", districts.count("Kicukiro"))
print("Gatsibo:", districts.count("Gatsibo"))

top_score = max(all_scores)
top_pos = all_scores.index(top_score)
print(f"The top student is {names[top_pos]} with a score of {top_score}.")

low_score = min(all_scores)
low_pos = all_scores.index(low_score)
print(f"The lowest student is {names[low_pos]} with a score of {low_score}.")
print(f"Top student attendance: {students[top_pos]['Att. %']}%")
print(f"Lowest student attendance: {students[low_pos]['Att. %']}%")