# -*- coding: utf-8 -*-
"""Week3_Eloge_MUGISHA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NrPM496I73eCwLQO-cfO9aWJw4-iXlh4
"""

print("Hello World!")

score = float(input("Enter the Marks: "))
if (score >= 85 ):
  grade = "A"
elif (score >= 70 ):
  grade = "B"
elif (score >= 60 ):
  grade = "C"
elif (score >= 50):
  grade = "D"
else:
  grade = "F"
print ("Grade: ", grade)

score = float(input("Enter the Marks: "))

attendance = float(input("Enter the Attendance percentage: "))

if (score >= 50 and attendance >= 75):
  print ("Validated")

elif (score >= 50 and attendance < 75):
  print ("Passed but the attendance is less than 75%")

else:
  print ("failed")

"""If the score >=50 comes before score >= 70, the score that are higher that 70 but less that 85 could be cought by the (score >= 50) condition and be incorrectly given grade D."""

Scores = [72, 85, 91, 64, 78, 47, 88, 55, 93, 61]

for score in Scores:
  if score >= 80:
    print("Top score: ", score)

scores = [72, 85, 91, 64, 78, 47, 88, 55, 93, 61]

total = 0
count = 0
passed = 0
failed = 0

for score in scores:
  total = total + score
  count = count + 1
  if score >= 50:
    passed = passed + 1
  else:
    failed = failed + 1

avarage = total / count

print ("Total: ", total)
print ("Count", count)
print ("Pass: ", passed)
print ("fail: ", failed)
print ("Avarage", avarage)

saved = 0
months = 0

while saved < 250000:
  saved = saved + 15000
  months = months + 1

print("It will take ", months, "months for you to buy a Laptop cost 250000 with your 15000 of savings ")

def get_grade (score):
  """Return the letter grade for a score."""

  if score >= 85:
    grade = "A"

  elif score >= 70:
    grade = "B"

  elif score >= 60:
    grade = "C"

  elif score >= 50:
    grade = "D"

  else:
    grade = "F"

  return grade

print (get_grade(91))
print (get_grade(76))
print (get_grade(43))

def pass_rate(scores):

  passed = 0

  for score in scores:
    if score >= 50:
      passed = passed + 1
  return( passed / len(scores) * 100)


Scores = [72, 85, 91, 64, 78, 47, 88, 55, 93, 61]

print(pass_rate(scores))

with open("week3_students 3.csv", "r") as f:
    lines = f.readlines()

print("Number of lines:", len(lines))
print("Header:", lines[0])
print("First student:", lines[1])

# There are 41 lines because there is 1 header line + 40 student records.

names = []

for line in lines[1:]:
    parts = line.strip().split(",")
    names.append(parts[1])

print("Count:", len(names))
print("First 5 names:", names[:5])

total = 0
valid = 0
bad = 0
bad_ids = []

for line in lines[1:]:
  parts = line.strip().split(",")

  try:
    score = int(parts[7])
    total += score
    valid += 1

  except ValueError:
    bad += 1
    bad_ids.append(parts[0])

avarage = total / valid

print("Valid: ", valid)
print("Bad: ", bad)
print("Bad_IDs", bad_ids)
print("Avarage: ", round(avarage, 1))

passed = 0
failed = 0

best_score = -1
best_name = ""

for line in lines[1:]:
  parts = line.strip().split(",")

  try:
    score = int(parts[7])

    if score >= 50:
      passed += 1

    else:
      failed += 1

    if score > best_score:
      best_score = score
      best_name = parts[1]

  except ValueError:
    continue

print("Passed: ", passed)
print("Failed: ", failed)
print("Top student: ", best_name)
print("Top  score: ", best_score)
print("Top grade", get_grade(best_score))

sums = {}
counts = {}

for line in lines[1:]:
    parts = line.strip().split(",")

    try:
        score = int(parts[7])
        district = parts[5]

        sums[district] = sums.get(district, 0) + score
        counts[district] = counts.get(district, 0) + 1

    except ValueError:
        continue

# Print every district's average
highest_district = ""
highest_average = -1

for district in sums:
    average = sums[district] / counts[district]

    print(district, "average:", round(average, 1))

    if average > highest_average:
        highest_average = average
        highest_district = district

print("Highest average district:", highest_district)
print("Highest average:", round(highest_average, 1))

with open("week3_report.txt", "w") as f:
    f.write("Week 3 Student Report\n")
    f.write("---------------------\n")
    f.write("Student count: 40\n")
    f.write("Valid scores: 37\n")
    f.write("Bad scores: 3\n")
    f.write("Average score: 75.3\n")
    f.write("Top student: Bonaventure Nkurunziza\n")
    f.write("Top score: 95\n")

with open("week3_report.txt", "r") as f:
    report = f.read()

print(report)

"""I would stop trusting the dataset if about 20% or more of the records were broken. Instead of skipping them, I would check the original data and correct the errors before using the dataset."""

