# -*- coding: utf-8 -*-
"""week 3 _ INEZA Aimee Peace Kennie

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d6BSWsnhaXc4t0GFVzfBF4EUQUSO7jnG
"""

ls

import pandas as pd

df = pd.read_excel("week3_students.xlsx")
df.to_csv("week3_students.csv", index=False)

with open("week3_students.csv", "r") as f:
    lines = f.readlines()

print("Number of lines:", len(lines))   # should be 41
print("Header:", lines[0].strip())
print("First student:", lines[1].strip())

# 1.1
for score in [91, 76, 64, 52, 43]:
    if score >= 85:
        print(score, "-> A")
    elif score >= 70:
        print(score, "-> B")
    elif score >= 60:
        print(score, "-> C")
    elif score >= 50:
        print(score, "-> D")
    else:
        print(score, "-> F")

# Exercise 1.2
tests = [(76, 92), (76, 68), (43, 95)]

for score, attendance in tests:
    if score >= 50 and attendance >= 75:
        print(f"score={score}, attendance={attendance} -> Validated")
    elif score >= 50 and attendance < 75:
        print(f"score={score}, attendance={attendance} -> Blocked: low attendance")
    else:
        print(f"score={score}, attendance={attendance} -> Failed")

scores = [72, 85, 91, 64, 78, 47, 88, 55, 93, 61]

#2.1
for s in scores:
    if s >= 80:
        print("Top score:", s)

#2.2
total = 0
count = 0
passed = 0
failed = 0

for s in scores:
    total += s
    count += 1
    if s >= 50:
        passed += 1
    else:
        failed += 1

average = total / count

print("Total:", total)
print("Count:", count)
print("Average:", average)
print("Passed:", passed)
print("Failed:", failed)

#2.3
savings = 0
months = 0

while savings < 250000:
    savings += 15000
    months += 1

print("Months needed:", months)

#3.1
def get_grade(score):
    """Return the letter grade for a numeric score."""
    if score >= 85:
        return "A"
    elif score >= 70:
        return "B"
    elif score >= 60:
        return "C"
    elif score >= 50:
        return "D"
    else:
        return "F"

for s in [91, 76, 43]:
    print(s, "->", get_grade(s))

#3.2
def pass_rate(score_list):
    passed = 0
    count = 0
    for s in score_list:
        count += 1
        if s >= 50:
            passed += 1
    return (passed / count) * 100

print(pass_rate(scores))

#4.1
with open("week3_students.csv", "r") as f:
    lines = f.readlines()

print("Number of lines:", len(lines))
print("Header:", lines[0].strip())
print("First student:", lines[1].strip())

#4.2
names = []

for line in lines[1:]:
    parts = line.strip().split(",")
    names.append(parts[1])

print("Count:", len(names))
print("First 5 names:", names[:5])

#5.1
valid = 0
bad = 0
bad_ids = []
total_score = 0

with open("week3_students.csv", "r") as f:
    lines = f.readlines()

for line in lines[1:]:
    parts = line.strip().split(",")
    try:
        score = int(parts[7])
        total_score += score
        valid += 1
    except ValueError:
        bad += 1
        bad_ids.append(parts[0])

avg_valid = total_score / valid

print("Valid:", valid)
print("Bad:", bad)
print("Bad IDs:", bad_ids)
print("Average valid score:", round(avg_valid, 1))

#5.2
passed = 0
failed = 0
best_score = -1
best_name = ""

for line in lines[1:]:
    parts = line.strip().split(",")
    try:
        score = int(parts[7])
    except ValueError:
        continue

    if score >= 50:
        passed += 1
    else:
        failed += 1

    if score > best_score:
        best_score = score
        best_name = parts[1]

print("Passed:", passed)
print("Failed:", failed)
print("Top student:", best_name, "-", best_score, "-", get_grade(best_score))

#5.3
sums = {}
counts = {}

for line in lines[1:]:
    parts = line.strip().split(",")
    try:
        s = int(parts[7])
    except ValueError:
        continue

    d = parts[5]
    sums[d] = sums.get(d, 0) + s
    counts[d] = counts.get(d, 0) + 1

for d in sums:
    print(d, round(sums[d] / counts[d], 1))

best_district = None
best_avg = -1

for d in sums:
    avg = sums[d] / counts[d]
    if avg > best_avg:
        best_avg = avg
        best_district = d

print("Highest district average:", best_district, round(best_avg, 1))

#bonus
report = f"""Week 3 Report
Students total: {valid + bad}
Valid scores: {valid}
Broken records: {bad}
Average valid score: {avg_valid:.1f}
Top student: {best_name} ({best_score}, {get_grade(best_score)})
"""

with open("week3_report.txt", "w") as f:
    f.write(report)

with open("week3_report.txt", "r") as f:
    print(f.read())